//标准库集合
#include"Pub_head.h"
//类引用
#include"class_Read_Input.h"
#include"class_vectors.h"
#include"class_Atom.h"
//常数变量
#include"PhysicsConstant.h"
#include"Parameters.h"
#include"extern_variables.h"
//模块调用
#include"LapackCPP.h"
//调用函数
#include"func.h"
